name: IOBattleStats
main: com.interordi.iobattlestats.IOBattleStats
version: 1.0
api-version: 1.13

commands:
  givehead:
    description: Get the head of a specific player.
    usage: /givehead [player_name]
